Resources:
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: username
          AttributeType: S
      KeySchema:
        - AttributeName: username
          KeyType: HASH
      TableName: ${self:custom.userTableName}
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2